# Generated by Django 2.0.1 on 2018-02-05 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_email_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucxMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('lastvisited', models.DateTimeField(auto_now=True)),
                ('e_mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.EmailAddress')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
